### ISSUE TITLE
Bug when attempting to merge precompiled and compiled versions of file together

### ISSUE THREAD

**Issue by andy-hanson** [broccolijs/broccoli-merge-trees#22]
I want to have both a preprocessed version of a file and the processed version output to the same directory.

Create this brocfile.js:

	var
		Filter = require('broccoli-filter'),
		funnel = require('broccoli-funnel'),
		merge = require('broccoli-merge-trees')

	function MyFilter(input, options) { Filter.call(this, input, options) }
	MyFilter.prototype = Object.create(Filter.prototype)
	MyFilter.prototype.extensions = [ 'filter-me' ]
	MyFilter.prototype.targetExtension = 'txt'
	MyFilter.prototype.processString = function(contents, relativePath) { return contents }

	module.exports = merge([
		'assets',
		new MyFilter(funnel('assets/filter-these', { srcDir: '/', destDir: 'filter-these' }))
	])

Then run:

	npm install broccoli broccoli-filter broccoli-funnel broccoli-merge-trees
	mkdir assets; mkdir assets/filter-these
	touch assets/filter-these/x.filter-me assets/static.txt

`broccoli build dist` works. `x.filter-me` and `x.txt` appear side-by-side in `dist/filter-these`.

`broccoli serve` works at first, but then `touch assets/static.txt` and it breaks:

	Built with error:
	Error: Merge error: file filter-these/x.filter-me exists in /home/andy/broccoli-bug/tmp/broccoli_merge_trees-input_base_path-dR2gWTSy.tmp/0 and /home/andy/broccoli-bug/tmp/broccoli_merge_trees-input_base_path-dR2gWTSy.tmp/1
	Pass option { overwrite: true } to mergeTrees in order to have the latter file win.
		at mergeRelativePath (/home/andy/broccoli-bug/node_modules/broccoli-merge-trees/index.js:118:19)
		at mergeRelativePath (/home/andy/broccoli-bug/node_modules/broccoli-merge-trees/index.js:142:15)
		at BroccoliMergeTrees.build (/home/andy/broccoli-bug/node_modules/broccoli-merge-trees/index.js:36:3)
		at /home/andy/broccoli-bug/node_modules/broccoli-merge-trees/node_modules/broccoli-plugin/read_compat.js:61:34
		at lib$rsvp$$internal$$tryCatch (/home/andy/broccoli-bug/node_modules/broccoli-merge-trees/node_modules/broccoli-plugin/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:493:16)
		at lib$rsvp$$internal$$invokeCallback (/home/andy/broccoli-bug/node_modules/broccoli-merge-trees/node_modules/broccoli-plugin/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:505:17)
		at lib$rsvp$$internal$$publish (/home/andy/broccoli-bug/node_modules/broccoli-merge-trees/node_modules/broccoli-plugin/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:476:11)
		at lib$rsvp$asap$$flush (/home/andy/broccoli-bug/node_modules/broccoli-merge-trees/node_modules/broccoli-plugin/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:1198:9)
		at process._tickCallback (node.js:355:11)

**Comment by stefanpenner** [comment]
It seems like a legit collision is occurring.  Many things across the broccoli ecosystem have been fixed/improved as well.

I will gladly reopen this, but ideally provide a repository with a Brocfile that demonstrates this issue. With that diagnosis will be super quick.
