### ISSUE TITLE
Error: ENOENT: no such file or directory, stat 

### ISSUE THREAD

**Issue by stefanpenner** [broccolijs/broccoli-merge-trees#52]
> i’ve been moving some files around, so i would assume it’s from that

```js
The Broccoli Plugin: [BroccoliMergeTrees] failed with:
Error: ENOENT: no such file or directory, stat '/Users/jedelman/workspace/voyager-web_trunk/tmp/broccoli_merge_trees-input_base_path-DQuSdorE.tmp/3/components/job-flavors.js'
    at Error (native)
    at Object.fs.statSync (fs.js:844:18)
    at buildEntry (/Users/jedelman/workspace/voyager-web_trunk/node_modules/broccoli-merge-trees/index.js:339:17)
    at BroccoliMergeTrees._mergeRelativePath (/Users/jedelman/workspace/voyager-web_trunk/node_modules/broccoli-merge-trees/index.js:247:19)
    at BroccoliMergeTrees._mergeRelativePath (/Users/jedelman/workspace/voyager-web_trunk/node_modules/broccoli-merge-trees/index.js:300:31)
    at BroccoliMergeTrees.build (/Users/jedelman/workspace/voyager-web_trunk/node_modules/broccoli-merge-trees/index.js:82:24)
    at /Users/jedelman/workspace/voyager-web_trunk/node_modules/broccoli-merge-trees/node_modules/broccoli-plugin/read_compat.js:61:34
    at tryCatch (/Users/jedelman/workspace/voyager-web_trunk/node_modules/broccoli-merge-trees/node_modules/broccoli-plugin/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:538:12)
    at invokeCallback (/Users/jedelman/workspace/voyager-web_trunk/node_modules/broccoli-merge-trees/node_modules/broccoli-plugin/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:553:13)
    at publish (/Users/jedelman/workspace/voyager-web_trunk/node_modules/broccoli-merge-trees/node_modules/broccoli-plugin/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:521:7)
    at flush (/Users/jedelman/workspace/voyager-web_trunk/node_modules/broccoli-merge-trees/node_modules/broccoli-plugin/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:2373:5)
    at nextTickCallbackWith0Args (node.js:419:9)
    at process._tickCallback (node.js:348:13)

The broccoli plugin was instantiated at: 
    at BroccoliMergeTrees.Plugin (/Users/jedelman/workspace/voyager-web_trunk/node_modules/broccoli-merge-trees/node_modules/broccoli-plugin/index.js:7:31)
    at new BroccoliMergeTrees (/Users/jedelman/workspace/voyager-web_trunk/node_modules/broccoli-merge-trees/index.js:42:10)
    at BroccoliMergeTrees (/Users/jedelman/workspace/voyager-web_trunk/node_modules/broccoli-merge-trees/index.js:36:53)
    at CoreObject.buildChildAppTree (/Users/jedelman/workspace/voyager-web_trunk/node_modules/ember-engines/lib/engine-addon.js:58:10)
    at CoreObject.buildEngineAppTree (/Users/jedelman/workspace/voyager-web_trunk/node_modules/ember-engines/lib/engine-addon.js:123:40)
    at CoreObject.buildCompleteJSTree (/Users/jedelman/workspace/voyager-web_trunk/node_modules/ember-engines/lib/engine-addon.js:186:42)
    at CoreObject.treeForEngine (/Users/jedelman/workspace/voyager-web_trunk/node_modules/ember-engines/lib/engine-addon.js:277:50)
    at CoreObject.treeFor (/Users/jedelman/workspace/voyager-web_trunk/node_modules/ember-engines/lib/engine-addon.js:644:25)
    at /Users/jedelman/workspace/voyager-web_trunk/node_modules/ember-cli/lib/broccoli/ember-app.js:498:20
    at Array.map (native)
    at EmberApp.addonTreesFor (/Users/jedelman/workspace/voyager-web_trunk/node_modules/ember-cli/lib/broccoli/ember-app.js:496:30)
    at EmberApp._addonTree (/Users/jedelman/workspace/voyager-web_trunk/node_modules/ember-cli/lib/broccoli/ember-app.js:899:36)
    at EmberApp._processedVendorTree (/Users/jedelman/workspace/voyager-web_trunk/node_modules/ember-cli/lib/broccoli/ember-app.js:944:20)
    at EmberApp._processedExternalTree (/Users/jedelman/workspace/voyager-web_trunk/node_modules/ember-cli/lib/broccoli/ember-app.js:975:21)
    at EmberApp.appAndDependencies (/Users/jedelman/workspace/voyager-web_trunk/node_modules/ember-cli/lib/broccoli/ember-app.js:1070:30)
    at EmberApp.javascript (/Users/jedelman/workspace/voyager-web_trunk/node_modules/ember-cli/lib/broccoli/ember-app.js:1199:34)
```

**Comment by stefanpenner** [comment]
May be related to broccoli-merge-trees or may be a broken upstream broccoli, it is not totally clear. But tracking here for now.

**Comment by stefanpenner** [comment]
Turns out this was not a broccoli-merge-tree bug directly, but the the input in question was a broken symlink, that confusingly was from input -> old broccoli tmp dir. Which resulted in us going down a rabbit whole.

I believe we can detect broken symlink case because if https://github.com/broccolijs/broccoli-merge-trees/blob/master/index.js#L339 fails then https://github.com/broccolijs/broccoli-merge-trees/blob/master/index.js#L196 provided the file. Which means it is a file that cannot be stat'd which implies it is a broken symlink.

Our choices then are:

a. ignore the file, and cary on
b. provide an error message saying the file in question is a broken symlink


@joliss  / @rwjblue / @hjdivad opinions?

**Comment by hjdivad** [comment]
> b. provide an error message saying the file in question is a broken symlink <-- inclined to take this path

Strong 👍  here.  Presumably the dangling symlink stems from some other misbehaving plugin; seems good to give users a clue as soon as we can.

**Comment by Kuzirashi** [comment]
I've encountered this error in Ember CLI 1.13.15. Will this issue be addressed in this plugin?

**Comment by joliss** [comment]
I think in general improving error messages for broken symlinks would be very useful.

I also think we shouldn't replicate the code for this into every plugin, but rather have some shared code.
