### ISSUE TITLE
deprecation warning on upgrade to 3.5.1

### ISSUE THREAD

**Issue by xiwcx** [broccolijs/broccoli-merge-trees#66]
Hi my team recently upgraded to 3.5.1 and we started seeing this warning:

```
WARNING: Invalid Broccoli2 node detected, falling back to broccoli-builder. Broccoli error:
---------------
Object: The .read/.rebuild API is no longer supported as of Broccoli 1.0. Plugins must now derive from broccoli-plugin. https://github.com/broccolijs/broccoli/blob/master/docs/broccoli-1-0-plugin-api.md
used as input node to BroccoliMergeTrees (TreeMerger (app))
-~- created here: -~-
    at BroccoliMergeTrees.Plugin (/Users/wcanavan/code/Mariana-Django/ui/node_modules/broccoli-plugin/index.js:7:31)
    at new BroccoliMergeTrees (/Users/wcanavan/code/Mariana-Django/ui/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:16:10)
    at Function.BroccoliMergeTrees [as _upstreamMergeTrees] (/Users/wcanavan/code/Mariana-Django/ui/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:10:53)
    at mergeTrees (/Users/wcanavan/code/Mariana-Django/ui/node_modules/ember-cli/lib/broccoli/merge-trees.js:85:33)
    at EmberApp.getAppJavascript (/Users/wcanavan/code/Mariana-Django/ui/node_modules/ember-cli/lib/broccoli/ember-app.js:1022:21)
    at EmberApp.toArray (/Users/wcanavan/code/Mariana-Django/ui/node_modules/ember-cli/lib/broccoli/ember-app.js:1623:12)
    at EmberApp.toTree (/Users/wcanavan/code/Mariana-Django/ui/node_modules/ember-cli/lib/broccoli/ember-app.js:1750:36)
    at module.exports (/Users/wcanavan/code/Mariana-Django/ui/ember-cli-build.js:138:16)
    at Builder.readBuildFile (/Users/wcanavan/code/Mariana-Django/ui/node_modules/ember-cli/lib/models/builder.js:52:14)
    at Builder.setupBroccoliBuilder (/Users/wcanavan/code/Mariana-Django/ui/node_modules/ember-cli/lib/models/builder.js:66:22)
    at new Builder (/Users/wcanavan/code/Mariana-Django/ui/node_modules/ember-cli/lib/models/builder.js:32:10)
    at ServeTask.run (/Users/wcanavan/code/Mariana-Django/ui/node_modules/ember-cli/lib/tasks/serve.js:45:55)
    at Promise.resolve.then (/Users/wcanavan/code/Mariana-Django/ui/node_modules/ember-cli/lib/models/command.js:243:46)
    at tryCatcher (/Users/wcanavan/code/Mariana-Django/ui/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:323:19)
    at invokeCallback (/Users/wcanavan/code/Mariana-Django/ui/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:495:31)
    at /Users/wcanavan/code/Mariana-Django/ui/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:559:14
    at flush (/Users/wcanavan/code/Mariana-Django/ui/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:2402:5)
    at process._tickCallback (internal/process/next_tick.js:61:11)

-~- (end) -~----------------

[API] Warning: The .read and .rebuild APIs will stop working in the next Broccoli version
[API] Warning: Use broccoli-plugin instead: https://github.com/broccolijs/broccoli-plugin
[API] Warning: Plugin uses .read/.rebuild API: [object Object]
```

I've read through https://github.com/ember-template-lint/ember-cli-template-lint/issues/345, https://github.com/ember-cli/ember-cli/issues/8198, https://github.com/broccolijs/broccoli/issues/374, & https://github.com/ember-cli/ember-cli/issues/8163 and tried upgrading or removing just about everything mentioned in any of them that is relevant to my application. Still, I haven't been able to figure out the source of the warning.

Is there anything in our package.json that is a known issue?

```
{
  "devDependencies": {
    "@ember/jquery": "^0.5.2",
    "@ember/optional-features": "^0.6.3",
    "babel-plugin-transform-decorators-legacy": "1.3.4",
    "babel-plugin-transform-object-rest-spread": "6.26.0",
    "broccoli-asset-rev": "^2.7.0",
    "broccoli-file-creator": "1.1.1",
    "c3": "0.4.21",
    "chalk": "2.3.2",
    "common-tags": "1.7.2",
    "d3": "3.5",
    "dotenv": "5.0.1",
    "ember-ajax": "^3.1.0",
    "ember-auto-import": "^1.2.13",
    "ember-changeset": "1.3.0",
    "ember-changeset-validations": "1.2.8",
    "ember-cli": "~3.5.1",
    "ember-cli-app-version": "^3.2.0",
    "ember-cli-autoprefixer": "0.8.1",
    "ember-cli-babel": "^6.16.0",
    "ember-cli-clock": "1.0.5",
    "ember-cli-code-coverage": "0.4.2",
    "ember-cli-content-security-policy": "1.0.0",
    "ember-cli-date-textbox": "1.1.0",
    "ember-cli-dependency-checker": "^3.0.0",
    "ember-cli-deploy": "1.0.2",
    "ember-cli-deploy-build": "1.1.1",
    "ember-cli-deploy-s3": "1.2.0",
    "ember-cli-eslint": "4.2.3",
    "ember-cli-file-saver": "1.2.2",
    "ember-cli-head": "0.4.0",
    "ember-cli-htmlbars": "^3.0.0",
    "ember-cli-htmlbars-inline-precompile": "^1.0.3",
    "ember-cli-inject-live-reload": "^1.8.2",
    "ember-cli-inline-content": "0.4.1",
    "ember-cli-mirage": "0.4.3",
    "ember-cli-moment-shim": "3.5.0",
    "ember-cli-release": "1.0.0-beta.2",
    "ember-cli-sass": "7.1.7",
    "ember-cli-shims": "^1.2.0",
    "ember-cli-sri": "^2.1.1",
    "ember-cli-string-helpers": "1.7.0",
    "ember-cli-stylelint": "2.2.0",
    "ember-cli-template-lint": "^1.0.0-beta.1",
    "ember-cli-uglify": "^2.1.0",
    "ember-component-attributes": "^0.1.1",
    "ember-component-css": "0.6.3",
    "ember-composable-helpers": "2.1.0",
    "ember-concurrency": "0.8.27",
    "ember-data": "~3.5.0",
    "ember-data-change-tracker": "0.7.3",
    "ember-did-change-attrs": "0.0.2",
    "ember-elsewhere": "1.0.4",
    "ember-exam": "1.0.0",
    "ember-export-application-global": "2.0.0",
    "ember-flatpickr": "2.3.0",
    "ember-freestyle": "0.10.0",
    "ember-fullcalendar": "1.8.0",
    "ember-get-config": "0.2.4",
    "ember-in-viewport": "3.0.0",
    "ember-inflector": "3.0.0",
    "ember-lifeline": "2.0.0",
    "ember-light-table": "1.13.2",
    "ember-link-action": "0.0.38",
    "ember-load-initializers": "^1.1.0",
    "ember-lodash": "4.18.0",
    "ember-moment": "7.6.0",
    "ember-multiselect-checkboxes": "0.11.1",
    "ember-native-dom-helpers": "0.6.2",
    "ember-power-select": "2.0.9",
    "ember-power-select-typeahead": "0.7.2",
    "ember-power-select-with-create": "0.6.1",
    "ember-promise-helpers": "1.0.6",
    "ember-qunit": "^3.4.1",
    "ember-qunit-nice-errors": "1.2.0",
    "ember-radio-button": "1.2.4",
    "ember-resolver": "^5.0.1",
    "ember-responds-to": "1.5.0",
    "ember-responsive": "2.0.8",
    "ember-route-action-helper": "2.0.6",
    "ember-simple-auth": "1.8.2",
    "ember-sinon": "1.0.1",
    "ember-sinon-qunit": "2.1.0",
    "ember-sortable": "1.11.2",
    "ember-source": "~3.5.1",
    "ember-test-selectors": "0.3.8",
    "ember-tooltips": "2.11.1",
    "ember-truth-helpers": "2.0.0",
    "ember-useragent": "0.5.0",
    "ember-websockets": "7.1.1",
    "ember-window-mock": "0.4.0",
    "eslint": "4.18.2",
    "eslint-config-airbnb-base": "11.3.2",
    "eslint-config-ember": "0.3.0",
    "eslint-config-mariana": "git+https://git@github.com/Mariana-Tek/eslint-config-mariana.git#v1.0.1",
    "eslint-plugin-compat": "2.2.0",
    "eslint-plugin-ember": "^5.2.0",
    "eslint-plugin-import": "2.9.0",
    "eslint-plugin-mariana-tek": "git+https://git@github.com/Mariana-Tek/eslint-plugin-mariana-tek.git#v1.0.0",
    "fs": "0.0.1-security",
    "intl": "1.2.5",
    "jquery.cardswipe": "1.3.0",
    "keyevent": "1.1.0",
    "loader.js": "^4.7.0",
    "moment-duration-format": "1.3.0",
    "path": "0.12.7",
    "qunit-dom": "^0.8.0",
    "request": "2.83.0",
    "request-promise-native": "1.0.5",
    "require-environment-variables": "1.1.2",
    "rsvp": "4.8.2",
    "semantic-ui-nag": "2.3.0",
    "stylelint": "9.10.1",
    "stylelint-config-standard": "18.2.0",
    "stylelint-declaration-strict-value": "1.1.2",
    "stylelint-order": "2.2.1",
    "sugar-date": "2.0.4",
    "svgstore": "2.0.3"
  },
  "ember-addon": {
    "paths": [
      "lib/@mariana/svgstore-inline",
      "lib/ember-cli-deploy-mariana"
    ]
  },
  "dependencies": {
    "chai": "4.1.2",
    "ember-cli-sentry": "3.0.0",
    "jQuery-Scanner-Detection": "1.2.1",
    "mock-socket": "^8.0.5",
    "urijs": "1.19.1"
  }
}
```

Let me know if I can provide any more information that would be helpful.

**Comment by okuryu** [comment]
Is this a valid bug? I also have the similar error.

**Comment by rwjblue** [comment]
What is on line 138 of your ember-cli-build.js file?

**Comment by xiwcx** [comment]
@rwjblue here's the context, i can provide more if necessary.

```js
134    
135        app.import('node_modules/jquery.cardswipe/dist/jquery.cardswipe.min.js');
136        app.import('node_modules/jQuery-Scanner-Detection/jquery.scannerdetection.js');
137    
138        return app.toTree();
139    };
140    
```

**Comment by xiwcx** [comment]
just checking in, are there any recommended steps for debugging this further?
